INTERVAL = 0.05  # seconds
FRAME_SIZE = 1500  # Bytes
FRAME_RATE = 500  # Frames/s

AREA_SIZE = 50  # km

NODE_DETECT_RANGE = 25  # km
NODE_COUNT = 4

ONE_SECOND = 1000000  # micro seconds
MILLI_SECOND = 1000
MAX_TIME = ONE_SECOND

SPEED_OF_LIGHT = 0.3
PROPAGATION_SPEED = SPEED_OF_LIGHT / 3

# SLOT_TIME must be divisible by STEP
exact_slot_time = int(NODE_DETECT_RANGE / PROPAGATION_SPEED)
divider = 10
SLOT_TIME = int(exact_slot_time / divider) * divider  # 250
STEP = int(SLOT_TIME / divider)  # 25

SIFS = SLOT_TIME
DIFS = SIFS + 2 * SLOT_TIME

NODE_FRAME_PROBABILITY = 0.05

MINIMUM_BACKOFF = 4
MAXIMUM_BACKOFF = 1024

FRAME_TIME = ONE_SECOND / FRAME_RATE + 2 * SLOT_TIME
RTS_DURATION = SIFS + FRAME_TIME + SIFS + FRAME_TIME + SIFS + FRAME_TIME
CTS_DURATION = SIFS + FRAME_TIME + SIFS + FRAME_TIME

ACK_TIMEOUT = SIFS + 2 * FRAME_TIME
CTS_TIMEOUT = SIFS + 2 * FRAME_TIME

KILLO = 1000
MEGA = 1000000
